[package]
name = "yavanna"
version = "0.3.0"
authors = ["Jordan <jordan@raboland.fr>"]
edition = "2018"

[dependencies]

[dependencies.gtk]
version = "0.9.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]

