on: [push]

name: CI

jobs:
  check:
    name: Yavanna
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy